services:
  api:
    image: rpm-api
    build: ./app/
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8008:8008"
    networks:
      - front-tier
      - back-tier

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'rpmesports'
      MYSQL_USER: 'rpm'
      MYSQL_PASSWORD: 'meuovo'
      MYSQL_ROOT_PASSWORD: 'meuovo'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - front-tier
      - back-tier
    volumes:
      - my-db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
      start_period: 20s

volumes:
  my-db:

networks:
  front-tier: {}
  back-tier: {}
